mimir:
  nginx:
    ingress:
      hosts:
        - host: metrics-monitoring.127-0-0-1.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: mimir-nginx-tls
          hosts:
            - metrics-monitoring.127-0-0-1.nip.io
